### ISSUE TITLE
Monitor Flask logs for non-fatal errors

### ISSUE THREAD

**Issue by jbukhari** [dag-hammarskjold-library/dlx-rest#1123]
Non-fatal errors can be occurring, indicating possibly unknown bugs, that would not be noticed unless the Flask logs are monitored and/or some alert system is in place. 

It may also be possible that undiscovered random network errors/database connection errors occur in the backend which prevent data from being updated as expected. These type of errors should also be discoverable in the logs
```[tasklist]
### Tasks
- [ ] Set up per-environment Sentry.io configurations
- [ ] Add Sentry.io configs to config.py
- [ ] Scale out Sentry.io subscription
```

**Comment by aaronhelton** [comment]
We could consider a tool like sentry.io, which has an easy plugin, to help monitor this. It provides a dashboard and a ticket-like system. I tested it out briefly with this application, on a different branch.

**Comment by jbukhari** [comment]
Specifically though, I was referring to errors that would be printed in the Flask logs. These would be Python errors indicating exceptions in the backend. They may not be exposed to the frontend, so they could be unnoticeable through the JS console/bug reporting.

**Comment by aaronhelton** [comment]
They provide a flask library to plugin and monitor for flask exceptions, which they log to a dashboard for investigation and action. Maybe I can demo it on Friday.
