### ISSUE TITLE
Implement Atlas Search

### ISSUE THREAD

**Issue by aaronhelton** [dag-hammarskjold-library/dlx-rest#1279]
```[tasklist]
### Tasks
- [x] Create default search indexes on the collections we want to search
- [x] Create an inventory of searches
- [x] Create a configuration setting to use Atlas Search or not (for benchmarking)
- [x] Create a switch to toggle Atlas Search
- [x] Add search selection option to DLX
- [x] Update queries in the API to leverage the aggregation pipeline
- [x] Add $search as one of the pipeline stages for target query types
```

**Comment by jbukhari** [comment]
Related to https://github.com/dag-hammarskjold-library/dlx/issues/231 and https://github.com/dag-hammarskjold-library/dlx/issues/232
